int32 mode
---
int32 period_t
float64 com_y_swing
float64 width_size
float64 t_dsp
float64 lift_height
float64 stand_height
float64 com_height
float64 imukp
float64 imukd
float64 target_pitch
float64 target_roll
float64 yaw_kp
float64 max_correction
float64 pitch_deadband
float64 roll_deadband
float64 hip_reflex_kp
float64 hip_reflex_kd
float64 knee_reflex_kp
float64 knee_reflex_kd
float64 ankle_reflex_kp
float64 ankle_reflex_kd
float64 reflex_max_deg