# 讀取 <location>/ZedCameraSet.ini 現值（request.load 未使用，僅作觸發旗標）
bool load
---
bool auto_exposure_gain
int32 exposure
int32 gain
bool auto_whitebalance
int32 whitebalance_temperature
int32 saturation
int32 denoising
int32 gamma
float32 zoomin
